# Generated by Django 2.2.27 on 2022-07-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220720_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='img_1',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='img',
            new_name='image',
        ),
    ]
