# Generated by Django 2.2.27 on 2022-07-20 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20220720_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='image_1',
            new_name='img_1',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='image',
            new_name='img',
        ),
    ]
