# Generated by Django 2.2.27 on 2022-07-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220720_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(default='your_default_image.jpg', upload_to='whatever'),
        ),
    ]
