# Generated by Django 2.2 on 2022-07-22 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_destination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
